# ============================================================
# 🧠  SETUP AND INSTALLATION
# ============================================================

# Working Environment:
# - Create a folder named "langgraph"
# - Open it in Visual Studio Code
# - All project code will be written inside this folder

# ------------------------------------------------------------
# 🔹 Installation Steps
# ------------------------------------------------------------

# 1. Create Virtual Environment:
# python -m venv venv

# 2. Activate Virtual Environment:
# venv/Scripts/activate

# 3. Install Required Libraries:
# pip install langgraph
# pip install langchain
# pip install langchain_openai
# pip install python-dotenv

# ------------------------------------------------------------
# 🔹 Testing Setup (Jupyter Notebook)
# ------------------------------------------------------------

# - Use Jupyter Notebook for better visualization of workflows
# - Test imports:
#   import langgraph
#   import langchain
# - Ensure everything is installed correctly


# ============================================================
# ⚙️ FIRST WORKFLOW — BMI CALCULATOR
# ============================================================

# Workflow Inputs:
# - Height (meters)
# - Weight (kg)

# Formula:
# BMI = weight / (height ** 2)

# ------------------------------------------------------------
# 🔹 State Definition
# ------------------------------------------------------------

# State contains:
# - weight: float
# - height: float
# - bmi: float

# Implemented using TypedDict


# ------------------------------------------------------------
# 🔹 Graph Construction Steps
# ------------------------------------------------------------

# 1. Create StateGraph with BMI state
# 2. Add node: calculate_bmi
# 3. Define edges:
#    start → calculate_bmi → end
# 4. Compile graph
# 5. Execute graph


# ------------------------------------------------------------
# 🔹 Node Function Logic
# ------------------------------------------------------------

# - Extract height and weight from state
# - Calculate BMI
# - Update state with BMI
# - Return updated state


# ------------------------------------------------------------
# 🔹 Execution
# ------------------------------------------------------------

# - Pass input:
#   {"weight": value, "height": value}
# - Output:
#   Updated state with BMI


# ============================================================
# ➕ EXTENDING WORKFLOW — BMI CATEGORY
# ============================================================

# New Feature:
# - Classify BMI into categories

# Categories:
# - Underweight (<18.5)
# - Normal (18.5–25)
# - Overweight / Obese

# ------------------------------------------------------------
# 🔹 Changes Made
# ------------------------------------------------------------

# - Added new state field:
#   category: string

# - Added new node:
#   label_bmi

# - Updated edges:
#   start → calculate_bmi → label_bmi → end


# ------------------------------------------------------------
# 🔹 Final Output
# ------------------------------------------------------------

# State now includes:
# - weight
# - height
# - bmi
# - category


# ============================================================
# 🤖 LLM-BASED WORKFLOW (BASIC)
# ============================================================

# Workflow:
# - Single node: llm_qa

# Functionality:
# - Takes question as input
# - Sends to LLM
# - Stores response

# ------------------------------------------------------------
# 🔹 State Definition
# ------------------------------------------------------------

# - question: string
# - answer: string


# ------------------------------------------------------------
# 🔹 Implementation
# ------------------------------------------------------------

# - Extract question from state
# - Send prompt to LLM (via LangChain)
# - Receive response
# - Update state with answer


# ------------------------------------------------------------
# 🔹 Workflow Structure
# ------------------------------------------------------------

# start → llm_qa → end


# ------------------------------------------------------------
# 🔹 Execution Example
# ------------------------------------------------------------

# Input:
# "How far is the moon from Earth?"

# Output:
# Answer generated by LLM

# Insight:
# - LangChain → handles LLM interaction
# - LangGraph → manages workflow


# ============================================================
# 🔗 PROMPT CHAINING WORKFLOW
# ============================================================

# Concept:
# - Multiple sequential LLM calls

# Example Workflow:
# 1. Generate outline
# 2. Generate blog using outline

# Flow:
# start → create_outline → create_blog → end


# ------------------------------------------------------------
# 🔹 State Definition
# ------------------------------------------------------------

# - title: string
# - outline: string
# - content: string


# ------------------------------------------------------------
# 🔹 Nodes
# ------------------------------------------------------------

# 1. create_outline:
#    - Generates blog outline using LLM

# 2. create_blog:
#    - Generates full blog using title + outline


# ------------------------------------------------------------
# 🔹 Key Benefit
# ------------------------------------------------------------

# - State evolves step-by-step
# - Intermediate outputs (outline) are accessible
# - More control compared to simple chains


# ------------------------------------------------------------
# 🔹 Homework Suggestion
# ------------------------------------------------------------

# - Add third node:
#   evaluate_blog
# - Rate blog based on outline
# - Update state and edges accordingly


# ============================================================
# 📌 SUMMARY & FINAL NOTES
# ============================================================

# Learned Concepts:
# - Creating sequential workflows
# - Defining state and nodes
# - Connecting nodes with edges
# - Compiling and executing graphs
# - Integrating LLMs via LangChain

# Key Approach:
# - Start simple (BMI example)
# - Gradually build complex workflows

# Insight:
# - LangGraph may feel heavy for simple workflows
# - But becomes powerful for complex, stateful systems


# ============================================================
# 🧾 CONCLUSION
# ============================================================

# - Practical introduction to LangGraph workflows
# - Covers:
#   → Setup and environment
#   → Sequential workflows (BMI)
#   → LLM-based workflows
#   → Prompt chaining

# - Demonstrates:
#   → State management
#   → Multi-step execution
#   → Integration of LangChain + LangGraph

# - Encourages hands-on practice to build real-world
#   Agentic AI systems effectively
# ============================================================
